channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python<=3.10.16
  - pip
  - pip:
    - mlflow<=3.1.1
    - cffi<=1.17.1
    - cloudpickle<=2.2.1
    - defusedxml<=0.7.1
    - graphviz<=0.20.3
    - lightgbm<=4.5.0
    - matplotlib<=3.7.5
    - numpy<=1.26.4
    - pandas<=2.2.3
    - psutil<=6.1.0
    - pyarrow<=18.1.0
    - scikit-learn<=1.5.2
    - scipy<=1.14.1
name: mlflow-env
